### ISSUE TITLE
Question, does LLVM 6.0 are supported?

### ISSUE THREAD

**Issue by lygstate** [doe300/VC4C#106]

**Comment by doe300** [comment]
In what function?
To compile VC4C? Yes
To be used as OpenCL pre-compiler? Not explicitly, but should be
To be used as LLVM library front-end? Not tested, but should be unless the internal LLVM AAPI changed in the areas used by VC4C (loading bitcode module, reading instructions)

**Comment by lygstate** [comment]
I means opencl pre-compiler
