### ISSUE TITLE
General usage

### ISSUE THREAD

**Issue by alexzk1** [doe300/VC4C#110]
1. No stdout output. So have to use -o file and do tricky stuffs instead in chaining pipes (unix way).
2. --hex option give 32 bits integers. What if gpu and cpu has different endianess? I would suggest array of 1 byte numbers there.

**Comment by doe300** [comment]
> What if gpu and cpu has different endianess?

The endianess of GPU and CPU are static. And for the Raspberry Pi they both are little endian, so it is the same. I used 32-bit words, since internally in the GPU they are also treated as 32-bit words.

**Comment by alexzk1** [comment]
Well, you do bigger job then "PI" - it is compiler for videochip. But maybe u're right and not so important.
