### ISSUE TITLE
cpack -G DEB "error"

### ISSUE THREAD

**Issue by rlsl** [doe300/VC4C#149]
hello everyone, I need help in the for Debian package, cpack -G DEB, the file vc4c-0.4-Linux.deb was generated perfectly in my Raspbian 64bits, however when I try to install a warning that the .deb architecture is amd64 not arm64. How can I fix this?

**Comment by doe300** [comment]
64-bit systems are not officially supported. If you want to install the VC4C package, you will need to build it yourself.

Note that there is no guarantee anything will actually work on a 64-bit Raspberry Pi OS (or any other 64-bit OS), see also https://github.com/doe300/VC4CL/issues/97.
