### ISSUE TITLE
Remove common expression

### ISSUE THREAD

**Issue by nomaddo** [doe300/VC4C#17]
```cl
kernel void sum_f16 (global float a[], global float b[], global float c[]) {
  int id = get_global_id(0);
  float16 x = vload16(id, b);
  float16 y = vload16(id, c);
  vstore16 (x * y + x * y + x * y, id, a);
}
```

https://gist.github.com/nomaddo/9a7921afd53d08cb34d736e7432b8036

In this code, it seems that the same calculation is performed repeatedly (line 59 and 60).
I imaged this such typical optimization (removing subcommon expression) is done by `clang`.

**Comment by nomaddo** [comment]
Output of `clang` include `fmuladd`. So sub-common expression elimination doesn't work.
With `-ffp-contract=off`, this optimization seem to be peformed.

**Comment by nomaddo** [comment]
One more thing: in line 59 ~ 63, dual-issue can be performed, but doesn't work.
In my imagination, we need instruction scheduling including such optimization?

**Comment by doe300** [comment]
> With `-ffp-contract=off`, this optimization seem to be peformed.

Since the VC4 doesn't support `fmuladd`, we can simply disable fused floating-point operations.

**Comment by nomaddo** [comment]
This problem seems to be solved.
