### ISSUE TITLE
Description of dependencies

### ISSUE THREAD

**Issue by nomaddo** [doe300/VC4C#40]
Now the dependencies of `.deb` package is as follows.

https://github.com/doe300/VC4C/blob/master/CMakeLists.txt#L344

I am wondering it is right:

- Is `llvm-3.9-dev`  is always necessary?  If `LLVMLIB_FRONTEND` is disabled, `VC4C` might not depend on it?
- Is `clang-3.9` is always necessary?  if `LLVMIR_FRONTEND` is disabled, `VC4C` doesn't depend on it?

@doe300 Any Idea?

**Comment by doe300** [comment]
I am investigating the dependencies of VC4C and also VC4CL and remove what is not necessary.

**Comment by nomaddo** [comment]
At least `VC4C` with `SPIRV-LLVM` doesn't need `llvm-3.9-dev`: it can run on docker image of `nomaddo/cross-rpi:0.1`.

**Comment by doe300** [comment]
I'm not done here. Now that I again have a stable internet connection, I can check the TODOs I left in the CMakeLists.txt (also for VC4CL)
