### ISSUE TITLE
Use clang-format

### ISSUE THREAD

**Issue by doe300** [doe300/VC4C#57]
We should use clang-format to make sure, we have a unified formatting.

Any comments on this?
Does anyone have a good template for clang-format, we could use?

This would also apply to the VC4CL project.

**Comment by nomaddo** [comment]
I agree with your opinion. Some files are unformatted and we dont want to care for format differences.
As a trial, I made some config to use clang-format.

This patch enable to

- `make clangformat` to make all source-code formatted.
- Check all source-codes are formatted in clang-format in circleci.

Format style is defined in `.clang-format`, which is created by `clang-format -style=LLVM -dump-config > .clang-format` now. You can choose code styles as you like.

**Comment by doe300** [comment]
Closed with #59
